POST http://localhost:8000/getting-started
Content-Type: application/json

{
    "email":"shuklaakas883@gmail.com"
}

###

POST http://localhost:8000/signup
Content-Type: application/json

{
    "email":"shuklaakas883@gmail.com",
    "password":"Akash@1234",
    "otp":"8126",
    "hash":"053779bf94efa6005a28c140fef8e0af6b4c9afe33d3c2f289698e9ec0172bef.1684741330236"
}

###

POST http://localhost:8000/login
Content-Type: application/json

{
    "email":"shuklaakas883@gmail.com",
    "password":"Akash@1234"
}


###
POST http://localhost:8000/forgot-password
Content-Type: application/json

{
    "email":"shuklakash663@gmail.com"
}

###

POST http://localhost:8000/confirm-email
Content-Type: application/json

{
    "email":"shuklakash663@gmail.com",
    "otp":"3719",
    "hash":"3c3ee19ecce993148b5e19fb7a5cc99e21061172445556a8b501540437fd1e17.1684121372114"
}

###
POST http://localhost:8000/new-pass
Content-Type: application/json

{
    "email":"ok@gmail.com",
    "password":"Password@123",
    "token":"3c3ee19ecce993148b5e19fb7a5cc99e21061172445556a8b501540437fd1e17.1684121372114"
}
###
GET http://localhost:8000/default
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNodWtsYWFrYXM4ODNAZ21haWwuY29tIiwiaWF0IjoxNjg0NzQxODExfQ.DYBeZoyAsbT4oh8x9UH9SI24gNN6QjDC2p-3vQDyxNs




###
POST http://localhost:8000/add-note
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNodWtsYWFrYXM4ODNAZ21haWwuY29tIiwiaWF0IjoxNjg0NzQxODExfQ.DYBeZoyAsbT4oh8x9UH9SI24gNN6QjDC2p-3vQDyxNs

{
    "title":"Rcb vs Srh 2",
    "description":"Lorem difasi skjnfs knbfs jdfbs uodf dfoif sdfsdfsdf sdfasfmdf df "
}
###
GET http://localhost:8000/default
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5lb3dAZ21haWwuY29tIiwiaWF0IjoxNjg0MzAzNzAxfQ.hhBQs1aB3nr17vj2TAQuQWzu7vUQ_pyPhVNzxbTKuss

###

POST http://localhost:8000/delete-note
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5lb3dAZ21haWwuY29tIiwiaWF0IjoxNjg0MzAzNzAxfQ.hhBQs1aB3nr17vj2TAQuQWzu7vUQ_pyPhVNzxbTKuss

{
    "id":"6465e129ecc273eddb18477b"
}
###
POST http://localhost:8000/edit-note
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5lb3dAZ21haWwuY29tIiwiaWF0IjoxNjg0MzAzNzAxfQ.hhBQs1aB3nr17vj2TAQuQWzu7vUQ_pyPhVNzxbTKuss

{
    "id":"646727081b14b9108597d3cd",
    "title":"rcb srh",
    "description":"rcb won by 8 wickets"
}

###

Get http://localhost:8000/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5lb3dAZ21haWwuY29tIiwiaWF0IjoxNjg0MzAzNzAxfQ.hhBQs1aB3nr17vj2TAQuQWzu7vUQ_pyPhVNzxbTKuss

